title: YAMB
author: Alessio Pagliari
description: YAMB Documentation

remote_theme: pmarsceill/just-the-docs

# search_enabled: false
aux_links:
  "YAMB on GitHub":
    - "//github.com/ale93p/yamb"
# color_scheme: "dark"
