title: NAMB
author: Alessio Pagliari
description: NAMB Documentation

url: https://apgl.xyz
enforce_ssl: apgl.xyz

remote_theme: pmarsceill/just-the-docs

# search_enabled: false
aux_links:
  "NAMB on GitHub":
    - "//github.com/ale93p/namb"
# color_scheme: "dark"
